fixtures:
  repositories:
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.2.0'
    stdlibfeatures:
      repo: 'git://github.com/ghoneycutt/puppet-module-stdlibfeatures.git'
      ref:  'v0.1.0'
    common:
      repo: 'git://github.com/ghoneycutt/puppet-module-common.git'
      ref:  'v1.0.2'
    afs:
      repo: 'git://github.com/Phil-Friderici/puppet-module-afs.git'
    beuser:
      repo: 'git://github.com/Ericsson/puppet-module-beuser.git'
    logaggregation:
      repo: 'https://gerrit.ericsson.se/puppet/puppet-module-logaggregation.git'
    nscd:
      repo: 'git://github.com/ghoneycutt/puppet-module-nscd.git'
    vas:
      repo: 'git://github.com/Ericsson/puppet-module-vas.git'
    nisclient:
      repo: 'git://github.com/Ericsson/puppet-module-nisclient.git'
    rpcbind:
      repo: 'git://github.com/ghoneycutt/puppet-module-rpcbind.git'
    nsswitch:
      repo: 'git://github.com/ghoneycutt/puppet-module-nsswitch.git'
    pam:
      repo: 'git://github.com/ghoneycutt/puppet-module-pam.git'
  symlinks:
    common_eis: "#{source_dir}"
